# Generated by Django 5.1.6 on 2025-02-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0003_rename_faixa_aulasconcluidas_faixa_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulasconcluidas',
            name='data_aula',
            field=models.DateField(auto_now=True),
        ),
    ]
